googleapis/google-auth-library-php

.travis.yml, composer.json
grpc side does not like dev-master.
=> Update firebase/php-jwt dependency

tests/ApplicationDefaultCredentialsTest.php, tests/AuthTokenFetcherTest.php, tests/ScopedAccessTokenTest.php
Fixes https://github.com/google/google-auth-library-php/issues/35
=> Remove unused code in tests

README.md
adds steps to use this auth library + instructions on downloading your application credentials
=> RFC: Add code example to readme

src/AppIdentityCredentials.php, src/ApplicationDefaultCredentials.php, tests/AppIndentityCredentialsTest.php, tests/mocks/AppIdentityService.php
=> adds AppIdentityCredentials

src/OAuth2.php
With PHP IDEs being able to provide smart assistance and context 
for code, it's necessary to add soft type hints through doc blocks.
This also helps humans when inspecting the library code visually.
Adds appropriate @var, @return and @param tags where possible.
I propose to do this gradually or the whole library.
=> Add doc-blocks to OAuth2 where appropriate to allow better analysis

src/CacheTrait.php, src/Middleware/AuthTokenMiddleware.php, src/Subscriber/AuthTokenSubscriber.php
this ensures the token callback receives the entire cache key
=> adds method to get full cache key

composer.json
=> semantic versioning for guzzle/psr7 dependency

src/ApplicationDefaultCredentials.php, src/CredentialsLoader.php, tests/Credentials/ServiceAccountCredentialsTest.php
=> simplifies loading of json keys

src/CacheTrait.php, tests/CacheTraitTest.php
=> adds hashing and shortening to enforce max key length

.travis.yml, CHANGELOG.md, composer.json, tests/CacheTraitTest.php, tests/FetchAuthTokenCacheTest.php, tests/Middleware/AuthTokenMiddlewareTest.php, tests/Middleware/ScopedAccessTokenMiddlewareTest.php, tests/Subscriber/AuthTokenSubscriberTest.php, tests/Subscriber/ScopedAccessTokenSubscriberTest.php
Once merged, we will tag `v1.0` for this library.
=> Prepare 1.0 Release

composer.json
=> allow firebase/jwt 5.0

src/Cache/MemoryCacheItemPool.php
=> Fixes wrong variable name

src/Credentials/AppIdentityCredentials.php, tests/Credentials/AppIndentityCredentialsTest.php
=> ensures onAppEngine returns true on Dev AppServer

composer.json
I've added `PHPUnit 5` support.
=> Support PHPUnit 5

src/HttpHandler/Guzzle5HttpHandler.php, tests/HttpHandler/Guzzle5HttpHandlerTest.php
=> fix guzzle5 handler merge options

src/Cache/SysVCacheItemPool.php, tests/Cache/SysVCacheItemPoolTest.php, tests/Cache/sysv_cache_creator.php
@dwsupplee Can you also take a look?
=> Added SystemV shared memory based CacheItemPool

src/Credentials/GCECredentials.php, tests/ApplicationDefaultCredentialsTest.php, tests/Credentials/GCECredentialsTest.php
=> Fixes usage of deprecated env var for GAE Flex

phpunit.xml.dist, src/Credentials/UserRefreshCredentials.php
=> Add a warning for 3 legged OAuth credentials

src/Credentials/GCECredentials.php
It seems 0.3s timeout is not enough and cause flaky sometimes: https://github.com/grpc/grpc/issues/12490
The PR is imitating [what Java does](https://github.com/google/google-auth-library-java/blob/cbc6c1062d5fe1920c6a641a4d63769b56267eb0/oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java#L76), who has retry and 500ms timeout.
=> Add retry and increase timeout for GCE credentials

src/CredentialsLoader.php
=> Update auth token url

CHANGELOG.md
- Add support for insecure credentials (#208)
=> Changelog for v1.4.0

src/Credentials/GCECredentials.php, tests/ApplicationDefaultCredentialsTest.php, tests/Credentials/GCECredentialsTest.php, tests/HttpHandler/Guzzle5HttpHandlerTest.php
It isn't clear to me how these tests ever passed previously. 😆
=> Fix failing tests

src/Credentials/AppIdentityCredentials.php, src/Credentials/GCECredentials.php, src/Credentials/InsecureCredentials.php, src/Credentials/ServiceAccountCredentials.php, src/Credentials/ServiceAccountJwtAccessCredentials.php, src/Credentials/UserRefreshCredentials.php
Closes: https://github.com/googleapis/google-auth-library-php/issues/71
/cc @bshaffer
=> Describe the arrays returned by fetchAuthToken

.gitattributes
This will make the composer install lighter
=> Proposing .gitattributes

src/ServiceAccountSignerTrait.php
=> Fix phpseclib existence check

README.md
=> docs: Fix README console terminology.

CHANGELOG.md
* [feat] Add utility for verifying and revoking access tokens. (#243)
* [docs] Fix README console terminology. (#242)
* [feat] Support custom scopes with GCECredentials. (#239)
* [fix] Fix phpseclib existence check. (#237)
=> chore: Update changelog for 1.6.0

src/Cache/Item.php
=> Cache item expiration correctly calculated when DST shifts

src/Cache/SysVCacheItemPool.php
=> fix: construct RuntimeException

CHANGELOG.md
* [feat] Add ID token to auth token methods. (#248)
* [feat] Add support for ES256 in `AccessToken::verify`. (#255)
* [fix] Let namespace match the file structure. (#258)
* [fix] Construct RuntimeException. (#257)
* [tests] Update tests for PHP 7.4 compatibility. (#253)
* [chore] Add a couple more things to `.gitattributes`. (#252)
=> chore: update changelog for 1.7.0

src/Credentials/ServiceAccountCredentials.php, src/Credentials/ServiceAccountJwtAccessCredentials.php, src/Credentials/UserRefreshCredentials.php, src/FetchAuthTokenCache.php, src/GetQuotaProjectInterface.php, src/Middleware/AuthTokenMiddleware.php, src/Subscriber/AuthTokenSubscriber.php, tests/FetchAuthTokenTest.php
Just typed up a possible implementation for the `x-goog-user-project` header implementation.
Other considerations
=> feat: add support for x-goog-user-project

src/ApplicationDefaultCredentials.php, src/Credentials/GCECredentials.php, tests/ApplicationDefaultCredentialsTest.php
Request for Comment - Yet another parameter seems like the only sane way to do this.
=> feat: add quotaProject param for extensible client options support

src/OAuth2.php
=> docs: document inconsistent behavior between jwt versions

phpunit.xml.dist, src/Credentials/UserRefreshCredentials.php, tests/Credentials/UserRefreshCredentialsTest.php
=> Remove SDK warning

src/FetchAuthTokenCache.php, src/Middleware/AuthTokenMiddleware.php, src/OAuth2.php, tests/FetchAuthTokenCacheTest.php, tests/HttpHandler/Guzzle5HttpHandlerTest.php, tests/Middleware/AuthTokenMiddlewareTest.php, tests/OAuth2Test.php, tests/Subscriber/AuthTokenSubscriberTest.php
addresses #289 and #286 
cc @ericnorris
=> feat: checks cache expiration and fixes oauth2 cache key

README.md, composer.json
Addresses #4 (that's right.... the fourth issue ever opened...)
=> chore(docs): add link to refdocs from composer and README

CHANGELOG.md
=> chore: update CHANGELOG for v1.11.1

src/ApplicationDefaultCredentials.php, src/Credentials/ServiceAccountCredentials.php, src/Credentials/ServiceAccountJwtAccessCredentials.php, src/Credentials/UserRefreshCredentials.php, tests/ApplicationDefaultCredentialsTest.php, tests/Credentials/ServiceAccountCredentialsTest.php, tests/Credentials/UserRefreshCredentialsTest.php, tests/fixtures/private.json, tests/fixtures2/private.json
At some point in time the specification changed from quota_project to quota_project_id.
=> fix: use quota_project_id instead of quota_project

src/Credentials/GCECredentials.php, tests/Credentials/GCECredentialsTest.php
=> fix: add expires_at to GCECredentials

src/FetchAuthTokenCache.php, tests/FetchAuthTokenCacheTest.php
=> fix: adds check for getClientName

CHANGELOG.md
*  feat: Add support for guzzlehttp/psr7 v2 (#357)
=> chore: prepare v1.18.0

src/Middleware/AuthTokenMiddleware.php
=> fix: ensure result of fetchAuthToken is an array

src/AccessToken.php, tests/AccessTokenTest.php
addresses https://github.com/googleapis/google-auth-library-php/issues/399
=> fix: firebase php-jwt decode

composer.json, src/AccessToken.php
addresses #416 by adding support for PHPSecLib3 (and maintaining support for PHPSecLib2)
=> feat: add support for phpseclib3

composer.json
=> chore(deps): update dependency psr/http-message

.gitignore, src/CredentialSource/FileSource.php, src/CredentialSource/UrlSource.php, src/CredentialSourceInterface.php, src/Credentials/ExternalAccountCredentials.php, src/CredentialsLoader.php, src/ExternalAccountCredentialSourceInterface.php, src/OAuth2.php, src/UpdateMetadataTrait.php, tests/ApplicationDefaultCredentialsTest.php, tests/CredentialSource/FileSourceTest.php, tests/CredentialSource/UrlSourceTest.php, tests/Credentials/ExternalAccountCredentialsTest.php, tests/OAuth2Test.php, tests/fixtures6/file_credentials.json, tests/fixtures6/url_credentials.json
=> feat: add support for BYOID / STS

README.md
=> chore: Add documentation for configuring workload identity federation

.github/release-please.yml
=> fix: Release Please version file config

.github/workflows/tests.yml, composer.json
reverts https://github.com/googleapis/google-auth-library-php/pull/532
=> chore: add back php 8.0
