- src/GCECredentials.php
- src/OAuth2.php
Fixes https://github.com/google/google-auth-library-php/issues/37
> Variables have different name in code and definition

- src/GCECredentials.php
I tracked down the intermittent error on the compute_engine test. When we connect to GCE to get the initial metadata, the call is set to have a timeout of 0.1s. That fails around 50% of the time. So I tested increasing the timeout:
failure rate:
* 0.1s: 53%
* 0.2s: 49%
* 0.25s: 10%
* 0.3s: 0%
> increase timeout on gce connection

- src/OAuth2.php
- tests/OAuth2Test.php
the call to [`generateCredentialsRequest`](https://github.com/google/google-auth-library-php/blob/master/src/OAuth2.php#L369), called from [`fetchAuthToken`](https://github.com/google/google-auth-library-php/blob/master/src/OAuth2.php#L420), does not include the client credentials. This results in a `400 Bad Request`
```json
{
"error": "invalid_request",
"error_description": "Missing parameter: client_id"
}
```
I have changed this so the credentials are added to the request if they've been supplied to the 0Auth client
> adds client id/secret to code,refresh,and password grant types

- src/OAuth2.php
- tests/OAuth2Test.php
Current implementation generates a url with the value `approvalPrompt`:
https://accounts.google.com/o/oauth2/auth?
response_type=code&
access_type=offline&
approvalPrompt=force
I cannot find any current documentation referencing `approval_prompt`, so I am thinking it's now deprecated. However, it definitely [existed at one point](http://www.riskcompletefailure.com/2013/12/are-you-using-approvalpromptforce.html) so it should be fixed or removed. I say we play it safe and just fix it.
> approvalPrompt should be approval_prompt

- src/ServiceAccountCredentials.php
- tests/ServiceAccountCredentialsTest.php
This allows [domain-wide auth](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) in the php client library
Currently, in order to take advantage of domain-wide auth, you have to set the `$sub` parameter in the constructor. The problem with this is you lose the consistency of locating the credentials JSON file that exists in `CredentialsLoader`.
Adding `setSub` allows calls to `CredentialsLoader::fromEnv` and `CredentialsLoader::fromWellKnownFile` to return the `ServiceAccountCredentials` object, which then can have `setSub` called on it to "impersonate" a user.
This is not my favorite solution, but it is the only real way I can get this to work in the client library without some very ugly work-arounds. An alternative would be to add `getAuth` to return the …
> allows the setting of subjects on the service account after the fact

- src/AppIdentityCredentials.php
- tests/AppIndentityCredentialsTest.php
- tests/mocks/AppIdentityService.php
When requesting multiple scopes on AppEngine, an error is thrown `An unknown scope was supplied.` This is because the library is passing a space-delimited string instead of an array.
> AppIdentityCredentials expects array for multiple scopes

- composer.json
- src/OAuth2.php
- tests/OAuth2Test.php
We use a specific vendor for the slim framework and jwt authentication ( tuupola/slim-jwt-auth ) which requires firebase 3.0,
The differences according to the firebase log are
- namespacing
- better PHP Doc
- Require a non-empty key to decode and verify a JWT
(https://github.com/firebase/php-jwt/commit/fa8a06e96526eb7c0eeaa47e4f39be59d21f16e1)
The unittests succeed with these changes.
> Upped dependency to Firebase 3.0, fixed use statements

- src/CredentialsLoader.php
According to:
http://php.net/manual/en/function.php-uname.php
It is recommended using PHP_OS if possible.
> Use PHP_OS constants instead of php_uname().

- README.md
Since we have releases, can we remove dev-master from the README?
> Removed dev-master from README.

- src/CredentialsLoader.php
The client library is already overriding *most* of these calls with the **v4** endpoint anyway (see [here](https://github.com/google/google-api-php-client/blob/master/src/Google/Client.php#L43)), so really leaving this as `v3` is scarier than upgrading it.
> update oauth2 token URI to v4

- src/Middleware/AuthTokenMiddleware.php
- src/Subscriber/AuthTokenSubscriber.php
- tests/Middleware/AuthTokenMiddlewareTest.php
- tests/Subscriber/AuthTokenSubscriberTest.php
This is an attempt to resolve https://github.com/google/google-api-php-client/issues/901 and provide a more elegant way for https://github.com/google/google-api-php-client/pull/905 and https://github.com/google/google-api-php-client/pull/925
> adds token callback to AuthToken Middleware & Subscriber

- src/ApplicationDefaultCredentials.php
- src/Credentials/GCECredentials.php
- tests/ApplicationDefaultCredentialsTest.php
- tests/Credentials/GCECredentialsTest.php
If a custom runtime is used in App Engine Flexible, or PHP is executing outside of `php-nginx` (in this environment, `SERVER_SOFTWARE` is [set explicitly](https://github.com/GoogleCloudPlatform/php-docker/blob/2be08b74359c6d5bfd54c058e86ada19b4bfb94b/php-nginx/fastcgi_params#L30)), the auth library tries to use `AppIdentityCredentials`, which fails because the [appengine php sdk](https://github.com/GoogleCloudPlatform/appengine-php-sdk) doesn't exist.
> explicitly set AppEngine Flexible to use GCE credentials

- src/OAuth2.php
- tests/OAuth2Test.php
Prevent overwriting the refreshToken with null when no refresh token is returned in fetchAuthToken method
Fixes https://github.com/google/google-auth-library-php/issues/130
> Do not overwrite refresh token with null

- src/ApplicationDefaultCredentials.php
- src/Cache/InvalidArgumentException.php
- src/Cache/Item.php
- src/Cache/MemoryCacheItemPool.php
- src/CacheTrait.php
- src/Credentials/AppIdentityCredentials.php
- src/FetchAuthTokenCache.php
- src/Middleware/AuthTokenMiddleware.php
- src/Middleware/ScopedAccessTokenMiddleware.php
- src/Subscriber/AuthTokenSubscriber.php
- src/Subscriber/ScopedAccessTokenSubscriber.php
- tests/Cache/ItemTest.php
- tests/Cache/MemoryCacheItemPoolTest.php
- tests/CacheTraitTest.php
- tests/Credentials/AppIndentityCredentialsTest.php
- tests/FetchAuthTokenCacheTest.php
- tests/FetchAuthTokenTest.php
- tests/Middleware/AuthTokenMiddlewareTest.php
- tests/Subscriber/AuthTokenSubscriberTest.php
Addresses #121 
Highlights:
- Adds `FetchAuthTokenCache` wrapper class to implement caching on anything implementing `FetchAuthTokenInterface`.
- Removes caching from all Middleware / Subscriber classes
- Bypasses caching (by setting the key to null) for `AppIdentityCredentials` - Caching here is handled by the [AppIdentityService](https://github.com/GoogleCloudPlatform/appengine-php-sdk/blob/master/google/appengine/api/app_identity/AppIdentityService.php#L168)
- Removes calls to `getCacheKey` from Cache Trait - that function does not exist as part of the trait, and as a result was causing some unexpected problems. The cache key is now explicitly passed in.
> moves caching to wrapper class 'FetchAuthTokenCache' and adds Memory cache

- src/ApplicationDefaultCredentials.php
Please see: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/156
Requests to the compute engine metadata server appear to time out indefinitely in app engine standard. This will prevent testing for compute engine if we already know we are on app engine.
> Use elseif construct when determining credentials

- composer.json
- tests/OAuth2Test.php
The [B.C. breaking changes](https://github.com/firebase/php-jwt/tree/v4.0.0#changelog) will not affect our libraries. Some exception types changed is the only real difference I could find.
> adds firebase/JWT ~4.0

- src/CredentialsLoader.php
- src/Middleware/AuthTokenMiddleware.php
- src/Middleware/ScopedAccessTokenMiddleware.php
- src/Subscriber/AuthTokenSubscriber.php
- src/Subscriber/ScopedAccessTokenSubscriber.php
- tests/Middleware/AuthTokenMiddlewareTest.php
- tests/Middleware/ScopedAccessTokenMiddlewareTest.php
- tests/Subscriber/AuthTokenSubscriberTest.php
- tests/Subscriber/ScopedAccessTokenSubscriberTest.php
For issue grpc/grpc#7881
A recent GFE reloadable flag rollout caused a few Cloud APIs to start rejecting some requests from gRPC PHP clients because in some cases, the 'Authorization' header key for the bearer token got directly sent to the server, and it violates HTTP/2 standards. I am hoping we can change the header key to lower case.
> Change authorization header key to lowercase

- README.md
The option is called `base_uri`: http://docs.guzzlephp.org/en/latest/quickstart.html
> Fix base_url option

- src/CacheTrait.php
Per PSR-6:
> Hit - A cache hit occurs when a Calling Library requests an Item by key and a matching value is found for that key, and that value has not expired, and the value is not invalid for some other reason. Calling Libraries SHOULD make sure to verify isHit() on all get() calls.
The `$cacheItem` response is never validated, and in the case of the recommended Stash library the response contains the expired data (presumably to provide access to the previous cache).
This should fix a recurring issue with authentication when using Stash for storing authentication tokens; which were failing to regenerate properly.  There is one open issue https://github.com/google/google-api-php-client/issues/1075, plus several other closed issues which appear to have misdiagnosed the issue.
> Fix for PSR-6 compliance to verify a hit

- src/CredentialsLoader.php
- tests/FetchAuthTokenTest.php
see #148 
cc @michaelbausor, @ryanmats
Is this useful?
Usage:
```php
$credentials = GCECredentials();
$client = ClientLoader::makeHttpClient($credentials, [
'base_url' => 'https://www.googleapis.com/taskqueue/v1beta2/projects/'
]);
$response = $client->get('myproject/taskqueues/myqueue');
```
> adds makeHttpClient from credentials

- src/Middleware/ScopedAccessTokenMiddleware.php
- src/OAuth2.php
- tests/OAuth2Test.php
> adds support for additional claims in JWT tokens

- .travis.yml
- composer.json
- src/HttpHandler/Guzzle5HttpHandler.php
- src/HttpHandler/Guzzle6HttpHandler.php
- tests/HttpHandler/Guzzle5HttpHandlerTest.php
- tests/HttpHandler/Guzzle6HttpHandlerTest.php
Allows the HTTP Handlers to be used asynchronously w/o breaking backwards compatibility with the auth library.
@dwsupplee @michaelbausor
> Adds async method to HTTP handlers

- composer.json
- tests/ApplicationDefaultCredentialsTest.php
- tests/BaseTest.php
- tests/Cache/ItemTest.php
- tests/Cache/MemoryCacheItemPoolTest.php
- tests/CacheTraitTest.php
- tests/Credentials/AppIndentityCredentialsTest.php
- tests/Credentials/GCECredentialsTest.php
- tests/Credentials/IAMCredentialsTest.php
- tests/Credentials/ServiceAccountCredentialsTest.php
- tests/Credentials/UserRefreshCredentialsTest.php
- tests/OAuth2Test.php
A simple version of #174.
Now, I'm just updating to [`PHPUnit 4.8.36`](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-4.8.md#4836---2017-06-21), keep all PHP versions support, and use the `PHPUnit\Framework\TestCase` notation instead of `PHPUnit_Framework_TestCase` while extending our TestCases. This will help us migrate to PHPUnit 6, that [no longer support snake case class names](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed-1).
> Use PHPUnit\Framework\TestCase instead of PHPUnit_Framework_TestCase

- tests/Credentials/IAMCredentialsTest.php
- tests/Credentials/ServiceAccountCredentialsTest.php
- tests/OAuth2Test.php
I've refactored some tests, using:
- `assertFalse` instead of `assertTrue` with `!` before the condition;
- `assertInternalType`, avoiding using `is_*` functions;
- `assertGreaterThan` for mathematical comparisons;
- `assertArrayHasKey` and `assertArrayNotHasKey` instead of `array_key_exists` and `isset` functions;
- `assertEquals` and `assertNotEquals` instead of comparisons.
> Refactoring tests

- src/ApplicationDefaultCredentials.php
- tests/ApplicationDefaultCredentialsTest.php
> fixes subscriber and middleware options

- composer.json
Google api client relies on guzzlehttp/psr7:^1.2
> fix - guzzlehttp/psr7 dependency version definition

- src/CredentialsLoader.php
- src/OAuth2.php
Removed useless else after return for more readability
> Removed useless else after return

- .gitignore
- src/Credentials/InsecureCredentials.php
- src/CredentialsLoader.php
- tests/Credentials/InsecureCredentialsTest.php
Adds support for insecure credentials, which can be used when calling APIs that don't require credentials (e.g. public buckets), emulators, or test services.
cc @tmatsuo @bshaffer @dwsupplee @jdpedrie
> Add support for InsecureCredentials

- src/Credentials/InsecureCredentials.php
- src/Credentials/UserRefreshCredentials.php
- src/FetchAuthTokenInterface.php
- src/SignBlobInterface.php
- tests/Credentials/InsecureCredentialsTest.php
- tests/Credentials/UserRefreshCredentialsTest.php
- tests/FetchAuthTokenCacheTest.php
Fixes backwards-incompatible change in #221.
> Move `getClientName()` to SignBlobInterface.

- src/Cache/SysVCacheItemPool.php
Closes: https://github.com/googleapis/google-auth-library-php/issues/225
The flag was added in order to closely simulate the same behavior we had before with `loadItems` being called in the constructor.
> Move loadItems out of constructor to avoid race condition

- src/Credentials/GCECredentials.php
- tests/Credentials/GCECredentialsTest.php
An attempt to fix https://github.com/googleapis/google-auth-library-php/issues/231
> Add a Metadata-Flavor HTTP header to the initial metadata request

- CHANGELOG.md
* [fix] Move loadItems call out of `SysVCacheItemPool` constructor. (#229)
* [fix] Add `Metadata-Flavor` header to initial GCE metadata call. (#232)
> Update changelog for 1.5.2

- src/ApplicationDefaultCredentials.php
- src/Credentials/GCECredentials.php
- tests/Credentials/GCECredentialsTest.php
This change adds support for custom scopes provided to GCECredentials, closes #238.
This change has been verified in Cloud Run. Note that as [documented](https://cloud.google.com/run/docs/securing/service-identity#access_tokens), the feature is available only in certain limited environments, including App Engine, Run and Functions. The App Engine context, in my testing, does not appear to be inclusive of the Flex environment.
> feat: Support custom scopes on GCECredentials

- composer.json
- src/AccessToken.php
- tests/AccessTokenTest.php
- tests/fixtures/federated-certs.json
This change adds JWT token verification and revokation to the PHP Auth library. It is essentially a migration of `Revoke.php` and `Verify.php` from the [API Client](https://github.com/googleapis/google-api-php-client/tree/master/src/Google/AccessToken) with some cleanup and new unit tests that don't rely on real service calls.
> feat: Add Verify and Revoke token functionality

- CHANGELOG.md
* [fix] Handle DST correctly for cache item expirations. (#246)
> chore: update changelog for 1.6.1

- tests/Credentials/AppIdentityCredentialsTest.php
- tests/Credentials/GCECredentialsTest.php
- tests/Credentials/IAMCredentialsTest.php
- tests/Credentials/InsecureCredentialsTest.php
- tests/Credentials/ServiceAccountCredentialsTest.php
- tests/Credentials/UserRefreshCredentialsTest.php
The test suite is file-based so this didn't throw an error, but since the classes in the tests folder are referenced in the composer.json in the autoload-dev section, we can prevent problems in the future 🤞
:octocat:
> fix: let namespace match the file structure

- README.md
- src/ApplicationDefaultCredentials.php
- src/Credentials/GCECredentials.php
- src/Credentials/ServiceAccountCredentials.php
- src/CredentialsLoader.php
- src/Middleware/AuthTokenMiddleware.php
- tests/ApplicationDefaultCredentialsTest.php
- tests/Credentials/GCECredentialsTest.php
- tests/Credentials/ServiceAccountCredentialsTest.php
- tests/Middleware/AuthTokenMiddlewareTest.php
This uses existing `Auth Token` methods to also return ID tokens
Adding a fifth parameter is not ideal, but there isn't really a better way to do it without either
1. Refactoring several methods to take an options array as the first parameter
2. Breaking B.C. and bumping this library a major version
> feat: Adds ID token to auth token methods

- composer.json
- src/AccessToken.php
- tests/AccessTokenTest.php
Verify an IAP token:
```php
use Google\Auth\AccessToken;
$token = new AccessToken();
$result = $token->verify($iapJwt, [
'certsLocation' => AccessToken::IAP_CERT_URL
]);
```
Some points of interest:
- The cache key, when `certsLocation` is set, is now a `sha1` of the location, to prevent collisions with multiple cert types
- Added a `cacheKey` option to override this in the `$options` array argument to `verify`
- The exceptions have changed slightly - when `IAP_CERT_URL` is provided as the `certLocation`, the message `federated sign-on certs expect "keys" to be set` now reads `certs expect "keys" to be set`. This is because the IAP certs are not federated sign-on certs.
- `ES256` verification requires the use of the library `kelvinmo/simplejwt`, which is in a pre-1.0 state.
> feat: Adds support for ES256 in AccessToken::verify

- src/AccessToken.php
- tests/AccessTokenTest.php
Woops, `:` is an invalid cache-key character according to PSR-0. Changing it to `|`.
> fix: invalid character in iap cert cache key

- src/AccessToken.php
- tests/AccessTokenTest.php
Our wrapper in `AccessToken` for verifying JWTs is made significantly less valuable because we are suppressing the exceptions thrown by the underlying libraries which tell us what went wrong.  We need to expose a way for the user to see what error took place. I see the following options as viable:
Add a method `getVerifyException` which returns the exception which was thrown:
```php
$token = new AccessToken();
if (!$result = $token->verify($jwt)) {
print($token->getVerifyException()->getMessage());
}
```
Add an optional third argument which will contain the error message when the call fails:
```php
$token = new AccessToken();
$result = $token->verify($token, [], $message);
if (!$result) {
print($message);
}
```
Add an option to throw the error/exception on failure:
```php
$token = new …
```
> feat: add option to throw exception in AccessToken::verify

- src/AccessToken.php
- tests/AccessTokenTest.php
This allows issuer to be passed to AccessToken::verify, providing support for any JWTs
> feat: add option to specify issuer in AccessToken::verify

- src/Credentials/AppIdentityCredentials.php
- src/Credentials/GCECredentials.php
- src/Credentials/ServiceAccountCredentials.php
- src/Credentials/ServiceAccountJwtAccessCredentials.php
- src/FetchAuthTokenCache.php
- src/ProjectIdProviderInterface.php
- tests/Credentials/AppIdentityCredentialsTest.php
- tests/Credentials/GCECredentialsTest.php
- tests/Credentials/ServiceAccountCredentialsTest.php
- tests/FetchAuthTokenCacheTest.php
- tests/mocks/AppIdentityService.php
Like a cross between #221 and #220. Provides for detection of a project ID on a Credentials instance.
Tested on GAE Standard 5.5 and 7.2 and Flex (which uses GCECredentials).
Closes #135.
> feat: Add getProjectId to credentials types which support it

- .github/workflows/tests.yml
- composer.json
- src/CredentialsLoader.php
- src/HttpHandler/Guzzle6HttpHandler.php
- src/HttpHandler/Guzzle7HttpHandler.php
- src/HttpHandler/HttpHandlerFactory.php
- tests/BaseTest.php
- tests/Credentials/GCECredentialsTest.php
- tests/FetchAuthTokenTest.php
- tests/HttpHandler/Guzzle6HttpHandlerTest.php
- tests/HttpHandler/Guzzle7HttpHandlerTest.php
- tests/HttpHandler/HttpHandlerFactoryTest.php
- tests/Middleware/AuthTokenMiddlewareTest.php
- tests/Middleware/ScopedAccessTokenMiddlewareTest.php
Greetings 👋
**Update 2020-06-27: [Guzzle 7.0 has been released](https://github.com/guzzle/guzzle/releases)**
Guzzle 7 is only in beta at the moment, but due to its popularity/once it's released I assume that many developers will want to use it, perhaps already today. This PR aims to make google/auth ready for that and is a prerequisite to making similar changes to [`google/cloud(-core)`](https://github.com/googleapis/google-cloud-php) and [`google/api-client`](https://github.com/googleapis/google-api-php-client).
- Updated composer.json
- ~Extracted a version helper into a dedicated method in `HttpHandlerFactory::getGuzzleVersion()` and replaced usages~ _(Reverted after review)_ 
- ~Updated test matrix to test all supported Guzzle Versions (5.x is covered by `--prefer-lowest`, 6.x by the …
> feat: Add support for Guzzle 7.x

- src/Credentials/GCECredentials.php
Guzzle 7 [separated `ConnectException` from `RequestException`](https://github.com/guzzle/guzzle/pull/2541). When we ping the GCE metadata server, if we aren't on GCE, we'll get a `ConnectException`, which, since it's no longer caught, will bubble up to the user.
> fix: catch ConnectException in GCE check

- src/ApplicationDefaultCredentials.php
For consistency, this should also exist on `getMiddleware`
> feat: Adds quotaProject option to getMiddleware

- src/ApplicationDefaultCredentials.php
- src/GCECache.php
- tests/ApplicationDefaultCredentialsTest.php
- tests/GCECacheTest.php
Addresses #297 
- New class `GCECache`
- `ApplicationDefaultCredentials` automatically caches `onGce` response using the same `$cacheOptions` and `$cache` passed into `getCredentials` and `getIdTokenCredentials`
- `$cacheOptions` are the same for `GCECache` and `FetchAuthTokenCache`. Is this ok?
- `key` option allows flexibility for cache key, which defaults to `google_auth_on_gce_cache` (do we need this?)
The biggest issue I see is not being able to set a different lifetime/prefix between GCE and Access Token caches. To address this, `ApplicationDefaultCredentials` could create a new `$cacheOptions` for `GCECache` and allow for keys like `gce_lifetime` and `gce_prefix`
```php
$cacheOptions = [
'lifetime' => 1500,
'prefix' => 'access_token_',
'gce_lifetime' => 3000,
'gce_prefix' => …
```
> feat: adds caching for call to ::onGce

- src/Credentials/GCECredentials.php
- tests/Credentials/GCECredentialsTest.php
Adds the ability to change from using the `default` service account in `GCECredentials`
See #303
> feat: add service account identity support to GCECredentials

- src/Credentials/GCECredentials.php
- src/FetchAuthTokenCache.php
- tests/FetchAuthTokenCacheTest.php
fixes https://github.com/googleapis/google-auth-library-php/issues/328
@Babacooll PTAL
> fix: ensure cached tokens are used for GCECredentials::signBlob

- src/Credentials/ServiceAccountCredentials.php
- src/Credentials/ServiceAccountJwtAccessCredentials.php
- src/OAuth2.php
- tests/Credentials/ServiceAccountCredentialsTest.php
- tests/OAuth2Test.php
See https://google.aip.dev/auth/4111#scope-vs-audience
cc @shinfan
> feat: allow ServiceAccountJwtAccessCredentials to sign scopes

- CHANGELOG.md
- composer.json
- src/AccessToken.php
- src/Iam.php
- src/Middleware/SimpleMiddleware.php
- src/OAuth2.php
- tests/ApplicationDefaultCredentialsTest.php
- tests/Credentials/GCECredentialsTest.php
- tests/Credentials/ServiceAccountCredentialsTest.php
- tests/Credentials/UserRefreshCredentialsTest.php
- tests/IamTest.php
- tests/OAuth2Test.php
Replaced the use of deprecated functions in **guzzlehttp/psr7** for googleapis/google-cloud-php#4247
This is done so that we can use 1.x and 2.x branches of the **guzzlehttp/psr7** package.
The version in composer.json has been bumped to a **minimum of 1.7** because the alternatives to the deprecated versions are available starting **1.7**
> feat: Adding support for guzzlehttp/psr7:^2.0

- .gitattributes
- .php-cs-fixer.dist.php
- tests/OAuth2Test.php
Misc fixes
- add `phpstan.neon.dist` to `.gitattributes` export-ignore
- require single quotes when possible in CS check
> chore: export-ignore phpstan.neon, add single_quote to cs

- src/CredentialsLoader.php
Currently, the following code doesn't work because the `public function updateMetadata` implementation in `CredentialsLoader` only checks for `access_token` but not `id_token`.
```
$target_audience = 'https://some-endpoint.a.run.app/';  // A service deployed on Google Cloud Run
$auth_credentials = ApplicationDefaultCredentials::getIdTokenCredentials($target_audience);
$updated = $auth_credentials->updateMetadata([]); // `$updated` is still empty
```
The proposing CL adds handling for `id_token` which support the above case.
> fix: `CredentialsLoader` should support `id_token`

- src/Cache/Item.php
- src/Cache/TypedItem.php
addresses #408 by adding clarity on the reason why we have both `Cache\Item` and `Cache\TypedItem`
> chore: better phpdoc for cache items

- src/HttpHandler/HttpHandlerFactory.php
- tests/HttpHandler/HttpHandlerFactoryTest.php
**_Guzzle 7 Only_**
This will help the user receive a more helpful error message when encountering Google API exceptions. For example, with the "reAuth" error:
**Before**
```
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:
{
"error": "invalid_grant",
"error_description": "reauth related error (rapt_required)",
"error_uri": "https://sup (truncated...)
in /path/to/project/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
```
**After**
```
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:
{
"error": "invalid_grant",
"error_description": "reauth related error …
```
> feat: double default truncateAt for guzzle error output

- src/ApplicationDefaultCredentials.php
- src/Credentials/GCECredentials.php
- tests/Credentials/GCECredentialsTest.php
Adds a method `GCECredentials::setIsOnGce`, so that if `ApplicationDefaultCredentials` already checks that the library is running on GCE, we do not need to check again in `GCECredentials`.
```php
if (ApplicationDefaultCredentials::onGce()) {
$creds = new GCECredentials();
$creds->setIsOnGce(true); // save the credentials a trip to the metadata server
}
```
> fix: do not call GCECredentials::onGCE if ADC has already checked

- src/HttpHandler/HttpHandlerFactory.php
The latest version of PHPStan is smart enough to ignore missing references when they're wrapped in a conditional with a call to `defined`, so we no longer have to ignore this line!
> chore: remove phpstan ignore

- .github/workflows/tests.yml
- src/FetchAuthTokenCache.php
- tests/FetchAuthTokenCacheTest.php
This is needed for https://github.com/googleapis/gax-php/pull/441
**Note**: We will also need to cherry-pick this commit into [v1.19.0](https://github.com/googleapis/google-auth-library-php/releases/tag/v1.19.0) and tag `v1.19.1` as well, to provide compatibility in GAX for PHP 7.0.
> feat: add getFetcher to FetchAuthTokenCache

- src/Credentials/UserRefreshCredentials.php
- src/OAuth2.php
- tests/Credentials/UserRefreshCredentialsTest.php
- tests/OAuth2Test.php
b/253077796
Adds support for accessing granted scopes on the OAuth2 service class
**Q: Does this need to be accessible by the end user?**
- Yes
**Q: If so, how will this be accessible by the end user?**
- Exposing a method such as `getGrantedScopes` on the `Credentials` object is sufficient for this library.
**Q: How is this different from the existing `getScopes` method?**
- It wouldn't be any different for the other credentials types, only for `OAuth2` and `UserRefreshCredentials`, because they get information back from the API
> feat: accessing granted scopes 

- tests/AccessTokenTest.php
In [current test logs](https://github.com/googleapis/google-auth-library-php/actions/runs/4865928966/jobs/8676865153), we get logs like this `Deprecated: Creation of dynamic property Google\Auth\Tests\AccessTokenTest::$jwt is deprecated in /Users/vishwarajanand/github/google-auth-library-php/tests/AccessTokenTest.php on line 47`
With this change, we want to remove them.
> chore: fix PHP Deprecation warnings in tests

- .gitignore
- src/OAuth2.php
- tests/OAuth2Test.php
In order to support [PKCE for OAuth2](https://datatracker.ietf.org/doc/html/rfc7636), adds the following **public** methods:
- `OAuth2::generateCodeVerifier(): string`
- `OAuth2::setCodeVerifier(string $codeVerifier): void`
- `OAuth2::getCodeVerifier(): string`
**Usage**
_Authorization Request_
```php
$auth = new OAuth2(['client_id' => $clientId, 'client_secret' => $clientSecret]);
// Example of how a developer might save the code verifier in a stateless application
// NOTE: calling "generateCodeVerifier" will enable PKCE
$_SESSION['code_verifier'] = $auth->generateCodeVerifier();
// The authorization URI will include "code_challenge" and "code_challenge_method"
// querystring parameters if a code verifier is supplied
// (e.g. https://example.com?code_challenge=[base64 …
```
> feat: add pkce support

- src/AccessToken.php
This is (hopefully) a fix for #457.
It happens specifically with phpseclib 3.x.
---
When using the `AccessToken` class to decode an ID token, the "Federated Sign On" certificates are stored in the PKCS8 format after which the ID token is decoded with `Firebase/JWT`:
```php
$payload = $this->callJwtStatic('decode', [
$token,
$keys,
]);
```
Source: [AccessToken.php#L246](https://github.com/googleapis/google-auth-library-php/blob/main/src/AccessToken.php#L246)
Part of decoding the JWT is verifying the token which happens with `openssl_verify`:
```php
$success = \openssl_verify($msg, $signature, $keyMaterial, $algorithm);
```
Source: [JWT.php#L306](https://github.com/firebase/php-jwt/blob/main/src/JWT.php#L306)
I have to be honest that I am completely lacking any knowledge about RSA keys and …
> fix: use PKCS8 by default for ID token verify

- src/Credentials/ImpersonatedServiceAccountCredentials.php
- tests/OAuth2Test.php
Standard PHPUnit is to have only one test class in each test file. Substitute multiple test classes with proper use of the phpunit `@group` tag
> chore: refactor oauth2 tests

- src/AccessToken.php
- tests/AccessTokenTest.php
addresses #463
Extracts `max-age` from the `Cache-Control` header in order to set the cache lifetime of the certs.
> feat: respect cache control for access token certs

- src/Middleware/AuthTokenMiddleware.php
- tests/FetchAuthTokenTest.php
- tests/Middleware/AuthTokenMiddlewareTest.php
> chore: Refactor Auth Token Middleware's token logic

- src/Credentials/ServiceAccountCredentials.php
- tests/Credentials/ServiceAccountCredentialsTest.php
- tests/FetchAuthTokenTest.php
This is also a "fix" because, this should always have been the case. We want to respect the "sub" field, and use the oauth token endpoint instead of SSJs when it's supplied.
> feat: respect sub for domain-wide delegation in service account creds

- phpunit.xml.dist
- src/Middleware/AuthTokenMiddleware.php
A PHP warning was introduced in https://github.com/googleapis/google-auth-library-php/pull/492 where we didn't check if one of the values of the array was set. 
```
$ vendor/bin/phpunit tests/Middleware/AuthTokenMiddlewareTest.php --filter testDoesNotAddAnAuthorizationHeaderOnNoAccessToken
PHPUnit 9.6.13 by Sebastian Bergmann and contributors.
PHP Warning:  Undefined array key "id_token" in src/Middleware/AuthTokenMiddleware.php on line 135
.                                                                   1 / 1 (100%)
Warning: Undefined array key "id_token" in src/Middleware/AuthTokenMiddleware.php on line 135
Time: 00:00.012, Memory: 8.00 MB
OK (1 test, 1 assertion)
```
This is not too concerning, since PHP will cast this to an empty string, but we should get rid of the warning by …
> chore: fix php warning in AuthTokenMiddleware

- src/AccessToken.php
Fixes a linting error caused in the latest version ([3.0.35](https://github.com/phpseclib/phpseclib/releases/tag/3.0.35)) of PHPSeclib due to the `AsymmetricKey::toString` function [having its return type changed](https://github.com/phpseclib/phpseclib/blame/4b1827beabce71953ca479485c0ae9c51287f2fe/phpseclib/Crypt/Common/AsymmetricKey.php#L97) from `string` to `string|array`
Splitting this PR: 
https://github.com/googleapis/google-auth-library-php/pull/513, will mark https://github.com/googleapis/google-auth-library-php/pull/515 as covered with this one.
> fix: lint error from new phpseclib

- src/Credentials/GCECredentials.php
- src/FetchAuthTokenCache.php
- tests/Credentials/GCECredentialsTest.php
- tests/FetchAuthTokenCacheTest.php
> fix: ID Token Caching for GCECredentials

- src/Credentials/ServiceAccountJwtAccessCredentials.php
Fixing two issues here:
1) Returning `type` and `expires_in` with the token in case of JWT keys. ref: https://github.com/googleapis/google-cloud-php/pull/6850#issuecomment-1872164327 ![Screenshot 2023-12-28 at 00 06 36](https://github.com/googleapis/google-auth-library-php/assets/7369612/f1934e41-4cce-43ee-bab0-6eaa27c64f5f)
2) Fixing lint issues with `AccessToken.php`:
The lint check is complaining about retuning `string|array` in `loadPhpsecPublicKey` method ([ref](https://github.com/googleapis/google-auth-library-php/actions/runs/7357834969/job/20030094538?pr=513)) and expects a `string` instead. I am not sure whether this is the best fix, but looks like `__toString` method ([ref](https://github.com/phpseclib/phpseclib/blob/498e67a0c82bd5791fda9b0dd0f4ec8e8aebb02d/phpseclib/Crypt/RSA.ph …
> feat: ServiceAccountJwtAccessCredentials omits expires_in and token_type

- src/AccessToken.php
- src/ServiceAccountSignerTrait.php
Unit Tests are working in my local. 
I linked the new auth library all the way upto `google-cloud-php` and ran storage system tests against PROD, and they pass. Hence, i am confident the changes are good to review.
> deprecate: remove support for phpseclib V2

- src/FetchAuthTokenCache.php
- tests/FetchAuthTokenCacheTest.php
- tests/mocks/TestFileCacheItemPool.php
- tests/mocks/test_file_cache_separate_process.php
- Allows `FetchAuthTokenCache` to cache the universe domain. 
- Enables this cache for `GCECredentials` by default, in order to save a network call.
> feat: add caching for universe domain

- src/CredentialSource/AwsNativeSource.php
Currently the value for `x-amz-date` is generated from [date](https://www.php.net/manual/en/function.date.php) function, but if user sets a different timezone other than UTC, the generated timestamp has an invalid timestamp.
This causes the following `SignatureDoesNotMatch` error when authenticating with Workload Identity Federation:
When the timezone is older than UTC:
```
{"error":"invalid_grant","error_description":"The given AWS signed request is expired."}
```
When the timezone is later than UTC:
```
{"error":"invalid_grant","error_description":"Received invalid AWS response of type SignatureDoesNotMatch with error message: Signature not yet current: 20240305T152423Z is still later than 20240305T063924Z (20240305T062424Z + 15 min.)"}
```
This happens because `date('Ymd\THis\Z')` …
> fix: use gmdate to format x-amz-date with UTC irrespective of timezone

- composer.json
- src/CredentialSource/ExecutableSource.php
- src/Credentials/ExternalAccountCredentials.php
- src/ExecutableHandler/ExecutableHandler.php
- src/ExecutableHandler/ExecutableResponseError.php
- tests/ApplicationDefaultCredentialsTest.php
- tests/CredentialSource/ExecutableSourceTest.php
- tests/Credentials/ExternalAccountCredentialsTest.php
- tests/ExecutableHandler/ExecutableHandlerTest.php
- tests/fixtures6/executable_credentials.json
addresses https://github.com/googleapis/google-auth-library-php/issues/523
> feat: add ExecutableSource credentials

- src/CredentialSource/AwsNativeSource.php
- src/CredentialSource/ExecutableSource.php
- src/CredentialSource/FileSource.php
- src/CredentialSource/UrlSource.php
- src/Credentials/ExternalAccountCredentials.php
- src/Credentials/GCECredentials.php
- src/Credentials/ImpersonatedServiceAccountCredentials.php
- src/Credentials/ServiceAccountCredentials.php
- src/Credentials/ServiceAccountJwtAccessCredentials.php
- src/Credentials/UserRefreshCredentials.php
- src/ExternalAccountCredentialSourceInterface.php
- src/OAuth2.php
- tests/Credentials/ExternalAccountCredentialsTest.php
- tests/Credentials/ServiceAccountCredentialsTest.php
- tests/Credentials/ServiceAccountJwtAccessCredentialsTest.php
- tests/Credentials/UserRefreshCredentialsTest.php
We made changes to how we calculate the `cacheKeys` in order to avoid collision for the oncoming support for the Caching update.
closes: #559
> feat: Change getCacheKey implementation for more unique keys

- README.md
fixes user reported typos in recently published caching docs (see https://github.com/googleapis/google-auth-library-php/pull/563#discussion_r1678714899)
> docs: fix import typo, add comment

- .repo-metadata.json
- composer.json
similar to https://github.com/googleapis/gax-php/pull/589, but for auth. Will allow `google/auth` to be added to cloud refdocs
see https://github.com/googleapis/google-cloud-php/pull/8047
> fix: minor changes to allow for refdoc regeneration

- .github/workflows/tests.yml
- composer.json
We are now 20 months past the EOL of PHP 8.0, and support should be dropped
This is also outside our "[Foundational PHP Support](https://github.com/google/oss-policies-info/blob/main/foundational-php-support-matrix.md)" 
See https://github.com/googleapis/gax-php/pull/619
See https://github.com/googleapis/google-cloud-php/pull/8449
> chore: drop php 8.0

- src/Logging/LoggingTrait.php
- tests/Logging/LoggingTraitTest.php
This adds the `rpcName` to the log when using gRPC.
reference: #628
> feat: Add the rpcName to the logged event
